"""Generate map-data.js: a world outline and a table of country pin positions.

Run once, or again when the source data changes. Output is committed, so the
site never fetches any of this at runtime.

    python make_map.py

Sources, all fetched at BUILD time and none of them shipped:
  world-atlas land-110m      the coastline, as TopoJSON
  world-atlas countries-110m polygon per country, for pin positions
  i18n-iso-countries codes   ISO numeric (what world-atlas keys on) to
                             alpha-2 (what a geo-IP lookup returns)

TopoJSON is decoded here rather than in the browser so the page needs no
library: arcs are delta-encoded integers against a quantised grid, which is
what makes the file small, and undoing that is about thirty lines.
"""

import io
import json
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "map-data.js")

LAND = "https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json"
COUNTRIES = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json"
CODES = "https://cdn.jsdelivr.net/npm/i18n-iso-countries@7/codes.json"

W, H = 1000, 500          # equirectangular, so the viewBox is exactly 2:1


def get(url):
    print("  fetching %s" % url.split("/")[-1])
    with urllib.request.urlopen(url, timeout=60) as r:
        return json.loads(r.read().decode("utf-8"))


def decode_arcs(topo):
    """Delta-decode and un-quantise every arc into lon/lat pairs."""
    sx, sy = topo["transform"]["scale"]
    tx, ty = topo["transform"]["translate"]
    out = []
    for arc in topo["arcs"]:
        x = y = 0
        pts = []
        for dx, dy in arc:
            x += dx
            y += dy
            pts.append((x * sx + tx, y * sy + ty))
        out.append(pts)
    return out


def ring(arcs, idx):
    """One ring, following arc indices; a negative index means run it backwards."""
    pts = []
    for i in idx:
        a = arcs[~i][::-1] if i < 0 else arcs[i]
        pts.extend(a[1:] if pts else a)
    return pts


def rings_of(geom, arcs):
    """Every ring in a geometry. land-110m wraps its MultiPolygon in a
    GeometryCollection, countries-110m does not -- handle both."""
    t = geom["type"]
    if t == "GeometryCollection":
        out = []
        for g in geom["geometries"]:
            out.extend(rings_of(g, arcs))
        return out
    if t == "Polygon":
        return [ring(arcs, r) for r in geom["arcs"]]
    if t == "MultiPolygon":
        return [ring(arcs, r) for poly in geom["arcs"] for r in poly]
    return []


def project(lon, lat):
    return ((lon + 180.0) / 360.0 * W, (90.0 - lat) / 180.0 * H)


def main():
    land = get(LAND)
    countries = get(COUNTRIES)
    codes = get(CODES)

    # ── the coastline, as one path ──────────────────────────────────────
    arcs = decode_arcs(land)
    # One decimal is about 40km at this scale -- far under what a 1000px-wide
    # map can resolve, and it roughly halves the file.
    parts = []
    for r in rings_of(land["objects"]["land"], arcs):
        pts = [project(lon, lat) for lon, lat in r]
        if len(pts) < 3:
            continue
        head = "M%.1f %.1f" % pts[0]
        tail = "".join("L%.1f %.1f" % p for p in pts[1:])
        parts.append(head + tail + "Z")
    path = "".join(parts)

    # ── a pin position per country ──────────────────────────────────────
    num2a2 = {c[2].lstrip("0") or "0": c[0] for c in codes}
    carcs = decode_arcs(countries)
    pins = {}
    for geom in countries["objects"]["countries"]["geometries"]:
        a2 = num2a2.get(str(geom.get("id", "")).lstrip("0"))
        if not a2:
            continue
        rs = rings_of(geom, carcs)
        if not rs:
            continue
        # the largest ring is the mainland; its mean is close enough for a pin
        big = max(rs, key=len)
        lon = sum(p[0] for p in big) / len(big)
        lat = sum(p[1] for p in big) / len(big)
        x, y = project(lon, lat)
        pins[a2] = [round(x, 1), round(y, 1), geom["properties"]["name"]]

    js = io.StringIO()
    js.write("// Generated by make_map.py — do not edit.\n")
    js.write("// Coastline and country pin positions, projected equirectangular\n")
    js.write("// into a %dx%d box. Built from Natural Earth 110m via world-atlas.\n" % (W, H))
    js.write("window.MAP = {\n")
    js.write('  w: %d, h: %d,\n' % (W, H))
    js.write('  land: "%s",\n' % path)
    js.write("  pins: {\n")
    for a2 in sorted(pins):
        x, y, name = pins[a2]
        js.write('    %s: [%g, %g, %s],\n' % (a2, x, y, json.dumps(name)))
    js.write("  }\n};\n")

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(js.getvalue())
    print("  wrote map-data.js  %.0f KB  (%d countries, %d path chars)"
          % (os.path.getsize(OUT) / 1024.0, len(pins), len(path)))


if __name__ == "__main__":
    main()
